# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NullcloudBackend < Formula
  desc "NullCloud backend server"
  homepage "https://github.com/we-work-in-the-cloud/backend-nullcloud"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v0.2.0/nullcloud-backend_v0.2.0_darwin_amd64.tar.gz"
      sha256 "a90ce32db7468f689db907d643e15f7c4592684d735741be72b0767ca10f870f"

      define_method(:install) do
        bin.install "nullcloud-backend"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v0.2.0/nullcloud-backend_v0.2.0_darwin_arm64.tar.gz"
      sha256 "64c7fb2baa2c8e317de343e7341f895f75bdb822d5173ff2bd36bbf6664a3b32"

      define_method(:install) do
        bin.install "nullcloud-backend"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v0.2.0/nullcloud-backend_v0.2.0_linux_amd64.tar.gz"
      sha256 "956a667a2e1b71379c2d79c995203fd8e95cc4db3138943d7321e97d0a22465e"
      define_method(:install) do
        bin.install "nullcloud-backend"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v0.2.0/nullcloud-backend_v0.2.0_linux_arm64.tar.gz"
      sha256 "f79031958e4833eb9e884dcfebeaf4f7ccd1ee3cc60b89e5b29223b987a2b1ab"
      define_method(:install) do
        bin.install "nullcloud-backend"
      end
    end
  end

  test do
    assert_match "port", shell_output("#{bin}/nullcloud-backend --help 2>&1", 2)
  end
end
