# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NullcloudBackend < Formula
  desc "NullCloud backend server"
  homepage "https://github.com/we-work-in-the-cloud/backend-nullcloud"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v0.1.0/nullcloud-backend_v0.1.0_darwin_amd64.tar.gz"
      sha256 "58a967d9c688d06c81dbc8c8e07d84a263333ca54a350d642890717d62a40ba9"

      define_method(:install) do
        bin.install "nullcloud-backend"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v0.1.0/nullcloud-backend_v0.1.0_darwin_arm64.tar.gz"
      sha256 "eb8eb91a770d4dbd28f802787c8e774a6759c4172c7e7c55f6576133429d732f"

      define_method(:install) do
        bin.install "nullcloud-backend"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v0.1.0/nullcloud-backend_v0.1.0_linux_amd64.tar.gz"
      sha256 "ba034e9c0a2bc010a0cb0f27fb11c341245ad0b289f0696c3276aa590bbdfd4d"
      define_method(:install) do
        bin.install "nullcloud-backend"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v0.1.0/nullcloud-backend_v0.1.0_linux_arm64.tar.gz"
      sha256 "27899c234664fbd96ce7ac079b5e9b7cec0e3d326a3bb7c0ae002286a493d330"
      define_method(:install) do
        bin.install "nullcloud-backend"
      end
    end
  end

  test do
    assert_match "port", shell_output("#{bin}/nullcloud-backend --help 2>&1", 2)
  end
end
