# This file was generated by GoReleaser. DO NOT EDIT.
cask "nullcloud-backend" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "a9861986821b439ed686b88a9e2e9ac17946ee9be991ed83e9841709777bf0ec"
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v#{version}/nullcloud-backend_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3cf167af0541338eaf785d1dee66f5c7d9191b0a54c27e0909c60d8275b1fc49"
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v#{version}/nullcloud-backend_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2fab1e3370b3d01776b312bb9572d2d91d7f9dcdfc56fc6d0bcb9d49e2ddea30"
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v#{version}/nullcloud-backend_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c4d2821b46aaf30bff04342614de362c00592813e214b1b3d651f3be800559af"
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v#{version}/nullcloud-backend_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "nullcloud-backend"
  desc "NullCloud backend server"
  homepage "https://github.com/we-work-in-the-cloud/backend-nullcloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nullcloud-backend"

  # No zap stanza required

end
