# This file was generated by GoReleaser. DO NOT EDIT.
cask "nullcloud-backend" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "5dacd7288c0ae676f787d8290d17522fecd86c5820a07301f7525ada1cb37b9b"
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v#{version}/nullcloud-backend_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0229d02e5026e573b41f82ad3b48859972c087ef23ffbdefe3b3b164360638e5"
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v#{version}/nullcloud-backend_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "208b19763b66005054ecbd77e184f92829b93788b69e1c3cf3115cebcbd8046a"
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v#{version}/nullcloud-backend_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "44bb072f44901862ba35a26513db5a6a10bbb8dbeb00da3e508c412b9c63731e"
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v#{version}/nullcloud-backend_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "nullcloud-backend"
  desc "NullCloud backend server"
  homepage "https://github.com/we-work-in-the-cloud/backend-nullcloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nullcloud-backend"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nullcloud-backend"]
  end

  # No zap stanza required

end
