# This file was generated by GoReleaser. DO NOT EDIT.
cask "nullcloud-backend" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "768d0b45cc55518a3d52a4685cc70c49036a82086f6830a428b2a98922b29def"
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v#{version}/nullcloud-backend_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e235b8e3329783fbb88c9d00f7a94b0577664357a5fccfc9bfb78e575a86b511"
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v#{version}/nullcloud-backend_v#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "06d82ee43bd9fdf85c99de6ba87a1cdba6e831f4270889e6e7f655f91c4660e9"
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v#{version}/nullcloud-backend_v#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "253af12bea720b5724e7393fbd648ca75f7905db5aafa97743a39c94beec8f79"
      url "https://github.com/we-work-in-the-cloud/backend-nullcloud/releases/download/v#{version}/nullcloud-backend_v#{version}_linux_arm64.tar.gz"
    end
  end

  name "nullcloud-backend"
  desc "NullCloud backend server"
  homepage "https://github.com/we-work-in-the-cloud/backend-nullcloud"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nullcloud-backend"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/nullcloud-backend"]
  end

  # No zap stanza required

end
